// This file is automatically generated by tools/generate-media-data.js.
// Do not edit this file manually. Update files in content/articles instead and re-run the generator.

import { Article } from "@/types/article";

export const ARTICLES: Article[] = [
  {
    id: "44",
    imageUrl: "/images/articles/44.png",
    title: "BigBMeetUp 5th edition to focus on ‘Artists of Qatar’",
    publicationDate: "2024-01-11",
    excerpt: "The 5th edition of BigBMeetUp will celebrate the ‘Artists in Qatar’ at Sheikh Faisal Bin Qassim Al Thani Museum on January 11.",
    category: "event",
    tags: [
      "BigBMeetUp",
      "Qatar",
      "artists",
      "Sheikh Faisal Bin Qassim Al Thani Museum",
      "cultural event"
    ],
    notes: "Publication name and exact publication date not given; date inferred from event date. Article focuses on the announcement and details of the event."
  },

  {
    id: "48",
    imageUrl: "/images/articles/48.jpg",
    title: "إطلاق النسخة الخامسة لـ \"BigBMeetup\"",
    publicationDate: "2024-01-10",
    excerpt: "انعقاد اجتماع لـ BIGBMEETUP يضم الفنانين والمصممين وناقش التعاون الثقافي في دبي.",
    category: "news",
    tags: [
      "BigBMeetup",
      "ثقافة",
      "فن",
      "دبي",
      "المعرض"
    ],
    notes: "التاريخ موضوع في الشكل 10 يناير دون ذكر السنة صريحة، 2024 هو تخمين بناء على السياق الزمني."
  },

  {
    id: "90",
    imageUrl: "/images/articles/90.jpg",
    title: "فولفو - قطر تستضيف ندوة حول الاستدامة",
    publication: "AUTO تراية",
    publicationDate: "2023-03-28",
    excerpt: "استضافت فولفو للسيارات ندوة حول الاستدامة بالتعاون مع مبادرة Big B Meet Up في معرضها، ناقشت موضوعات البيئة والاستدامة والمستقبل الأخضر.",
    category: "event",
    tags: [
      "فولفو",
      "قطر",
      "استدامة",
      "بيئة",
      "مبادرة",
      "Big B Meet Up"
    ],
    notes: "التاريخ تقريبي بناءً على الرقم الظاهر في الإعلان 1443 هـ الذي يطابق 2023 ميلادي تقريبًا."
  },

  {
    id: "112",
    imageUrl: "/images/articles/112.jpg",
    title: "Qatar’s first Forest School at ISL Qatar marks its first anniv with #bigbmeetup",
    publication: "Qatar Tribune",
    publicationDate: "2022-11-01",
    excerpt: "International School of London (ISL) Qatar celebrated the first anniversary of its Forest School with a #bigbmeetup event.",
    category: "news",
    tags: [
      "Qatar",
      "Forest School",
      "ISL Qatar",
      "anniversary",
      "bigbmeetup"
    ],
    notes: "The article is partially obscured; excerpt is inferred from visible text."
  },

  {
    id: "91",
    imageUrl: "/images/articles/91.jpg",
    title: "فولفو تستضيف حلقة نقاشية حول الاستدامة في قطر",
    publication: "الشرق",
    publicationDate: "2021-12-21",
    excerpt: "استضافت فولفو للسيارات دورة نقاشية حول الاستدامة بتنظيم مبادرة Big B Meet Up في مقرها بحضور خبراء ومختصين لمناقشة التطور في استراتيجيات الاستدامة في قطر.",
    category: "event",
    tags: [
      "فولفو",
      "استدامة",
      "قطر",
      "مبادرة",
      "Big B Meet Up"
    ],
    notes: "التاريخ مأخوذ من رقم الإصدار والتاريخ الظاهران في أعلى الصفحة. المقال مكتوب بالعربية ويتعلق بحلقة نقاش حول الاستدامة تستضيفها فولفو في قطر."
  },

  {
    id: "87",
    imageUrl: "/images/articles/87.jpg",
    title: "Volvo hosts panel discussion on sustainability in Qatar",
    publication: "The Peninsula",
    publicationDate: "2021-12-14",
    excerpt: "Volvo held a panel discussion on sustainability in Qatar featuring key figures such as the Ambassador of Sweden to Qatar, Chairman of Friends of Nature, and Volvo's Managing Director.",
    category: "news",
    tags: [
      "Volvo",
      "sustainability",
      "Qatar",
      "panel discussion",
      "environment",
      "automotive"
    ]
  },

  {
    id: "88",
    imageUrl: "/images/articles/88.jpg",
    title: "Volvo hosts panel discussion on sustainability importance",
    publication: "Qatar Tribune",
    publicationDate: "2021-12-14",
    excerpt: "Volvo cars recently hosted a panel discussion at its showroom on the central ...",
    category: "news",
    tags: [
      "Volvo",
      "panel discussion",
      "sustainability",
      "Qatar"
    ],
    notes: "Publication date extracted from the image. Full article text and URL are not fully visible."
  },

  {
    id: "89",
    imageUrl: "/images/articles/89.jpg",
    title: "Volvo hosts panel discussion on sustainability importance",
    publication: "Qatar Tribune",
    publicationDate: "2021-12-14",
    excerpt: "Volvo cars recently hosted a panel discussion at its showroom on the central theme of sustainability in association with 'Big B Meet Up' started by Bosco Menezes.",
    category: "news",
    tags: [
      "Volvo",
      "sustainability",
      "panel discussion",
      "Qatar",
      "environmentalism"
    ],
    notes: "Date inferred from the newspaper header. No URL provided. Some names and organizations mentioned for context."
  },

  {
    id: "77",
    imageUrl: "/images/articles/77.jpg",
    title: "ISL Qatar launches the Forest School Project",
    publication: "GULF TIMES",
    publicationDate: "2021-11-11",
    excerpt: "ISL Qatar has launched the Forest School Project to promote outdoor education and environmental awareness among students.",
    category: "news",
    tags: [
      "ISL Qatar",
      "Forest School",
      "education",
      "environment",
      "Qatar"
    ],
    notes: "Publication date is taken from the webpage header timestamp."
  },

  {
    id: "81",
    imageUrl: "/images/articles/81.jpg",
    title: "ISL launches Forest School Project",
    publication: "Qatar Tribune",
    publicationDate: "2021-11-09",
    excerpt: "The International School of London (ISL) has launched a Forest School Project aimed at promoting sustainability and environmental awareness.",
    category: "news",
    tags: [
      "ISL",
      "Forest School",
      "sustainability",
      "Qatar",
      "environment"
    ]
  },

  {
    id: "78",
    imageUrl: "/images/articles/78.jpg",
    title: "ISL Qatar launches the Forest School Project",
    publication: "internationalschoolsearch.com",
    publicationDate: "2021-11-04",
    excerpt: "ISL Qatar hosted community outreach event #bigbmeetup's 'Estedama' during Qatar Sustainability Week, launching the Forest School Project and discussing sustainability.",
    category: "news",
    tags: [
      "ISL Qatar",
      "Forest School Project",
      "bigbmeetup",
      "sustainability",
      "Qatar"
    ],
    notes: "Exact source publication date is based on article posting date; full URL not provided."
  },

  {
    id: "76",
    imageUrl: "/images/articles/76.jpg",
    title: "International School of London-Qatar launches Forest School Project",
    publication: "The Peninsula",
    publicationDate: "2021-11-03",
    excerpt: "International School of London-Qatar has launched the Forest School Project.",
    category: "news",
    tags: [
      "education",
      "environment",
      "Qatar"
    ],
    notes: "Publication date and time are clearly stated; no full article URL provided in the clipping."
  },

  {
    id: "69",
    imageUrl: "/images/articles/69.jpg",
    title: "Four prominent women in sports and wellness meet at #BigBMeetUp",
    publication: "The Peninsula",
    publicationDate: "2021-02-14",
    excerpt: "Four prominent women in sports and wellness gathered at the #BigBMeetUp event to discuss and promote Qatar sportswomen.",
    category: "news",
    tags: [
      "sports",
      "wellness",
      "women",
      "Qatar",
      "community",
      "event"
    ],
    notes: "Last updated date is 2021-11-02 but publication date is considered primary for the article date."
  },

  {
    id: "67",
    imageUrl: "/images/articles/67.jpg",
    title: "Four Female Athletes Join the #BigBMeetUp Sports Day Episode at ISL Qatar",
    publication: "Marhaba Qatar Destination Guide",
    publicationDate: "2021-02-11",
    excerpt: "The first-ever ‘VIRTU-REAL’ and 34th episode of the weekly #bigbmeetup was hosted at the International School of London (ISL) Qatar…",
    category: "event",
    tags: [
      "sports",
      "female athletes",
      "ISL Qatar",
      "community",
      "BigBMeetUp"
    ],
    notes: "The full article URL is not provided in the clipping."
  },

  {
    id: "57",
    imageUrl: "/images/articles/57.png",
    title: "Celebrating adventurers who flew Qatar’s flag across globe",
    publication: "The Peninsula",
    publicationDate: "2020-02-04",
    excerpt: "A community event praised adventurers from Qatar who have represented the nation globally by flying its flag during their travels and achievements.",
    category: "news",
    tags: [
      "Qatar",
      "adventurers",
      "community",
      "flag",
      "travel",
      "event"
    ],
    notes: "Publication date is clearly stated as 04 Feb 2020; full article URL is not visible in the image."
  },

  {
    id: "59",
    imageUrl: "/images/articles/59.png",
    title: "Four Qatari adventurers share their inspiring stories",
    publication: "Gulf Times",
    publicationDate: "2020-02-03",
    excerpt: "Four exceptional Qatari adventurers shared their extraordinary stories during a recent gathering.",
    category: "community",
    tags: [
      "Qatar",
      "adventure",
      "inspiration",
      "community"
    ],
    notes: "Publication date and category inferred from article text and webpage layout; full article URL not provided."
  },

  {
    id: "58",
    imageUrl: "/images/articles/58.png",
    title: "#Bigbmeetup 6.0: Championing Arab Adventurers",
    publication: "iloveqatar.net",
    publicationDate: "2020-01-21",
    excerpt: "Bigbmeetup 6.0 event featuring Arab adventurers at Altitude Elite, Lusail Marina on 1st Feb 2020.",
    category: "event",
    tags: [
      "Bigbmeetup",
      "Arab adventurers",
      "community",
      "event",
      "Qatar"
    ],
    notes: "Publication date derived from posting date; article updated 2020-02-02."
  },

  {
    id: "50",
    imageUrl: "/images/articles/50.png",
    title: "إطلاق النسخة الخامسة BigBMeetUp تحت عنوان «فنانون قطر» بالتعاون مع متحف الشيخ فيصل بن قاسم آل ثاني",
    publicationDate: "2020-01-06",
    excerpt: "تحتفل النسخة الخامسة من BigBMeetUp «فنانون في قطر» في متحف الشيخ فيصل بن قاسم آل ثاني.",
    category: "event",
    tags: [
      "BigBMeetUp",
      "فنانون قطر",
      "متحف الشيخ فيصل بن قاسم آل ثاني",
      "الدوحة",
      "فن معاصر"
    ],
    notes: "تاريخ النشر مأخوذ من نص داخل المقال، ولكن لم تذكر اسم الصحيفة أو الموقع الناشر."
  },

  {
    id: "22",
    imageUrl: "/images/articles/22.jpg",
    title: "Bigbmeetup 3.0: Celebrating people who are differently abled",
    publication: "The Peninsula",
    publicationDate: "2019-04-23",
    excerpt: "Bigbmeetup 3.0 held at the Al Aziziya Boutique Hotel on Saturday.",
    category: "event",
    tags: [
      "Bigbmeetup",
      "differently abled",
      "community",
      "event"
    ],
    notes: "Publication date inferred from article timestamp."
  },

  {
    id: "12",
    imageUrl: "/images/articles/12.jpg",
    title: "Pearls of wisdom",
    publication: "Gulf Times",
    publicationDate: "2019-02-11",
    excerpt: "7 sport persons urge people to listen to their bodies and get active, on the eve of National Sport Day.",
    category: "feature",
    tags: [
      "sports",
      "health",
      "National Sport Day",
      "Qatar",
      "community"
    ],
    notes: "Publication date inferred from visible date Monday, February 11 2019; full article details on pages 4-5 not available in image."
  },

  {
    id: "14",
    imageUrl: "/images/articles/14.jpg",
    title: "Qatar set for National Sport Day celebration",
    publication: "Gulf Times",
    publicationDate: "2019-02-11",
    excerpt: "Qatar is set to celebrate National Sport Day tomorrow and different organizations and groups of people are taking part in various activities throughout the occasion.",
    category: "news",
    tags: [
      "Qatar",
      "National Sport Day",
      "sports",
      "community",
      "event",
      "health",
      "fitness"
    ],
    notes: "Publication date derived from newspaper header. The article focuses on National Sport Day activities and a related community event featuring speakers and athletes."
  },

  {
    id: "104",
    imageUrl: "/images/articles/104.jpg",
    title: "US embassy celebrates ‘American Cultural Day’",
    excerpt: "The US embassy in Qatar organized 'American Cultural Day' on July 4 to celebrate US Independence Day and 50 years of Qatar-US diplomatic relations, featuring music, panel discussions and cultural exchange.",
    category: "event",
    tags: [
      "US embassy",
      "American Cultural Day",
      "Qatar-US relations",
      "Independence Day",
      "cultural exchange",
      "bigbmeetup"
    ],
    notes: "Publication name and date not visible; partial URL provided without full URL."
  },

  {
    id: "106",
    imageUrl: "/images/articles/106.jpg",
    title: "US Embassy celebrates American Cultural Day",
    publication: "THE PENINSULA",
    excerpt: "The US Embassy in Qatar celebrated American Independence Day with an American Cultural Day event featuring panel discussions and cultural exchanges.",
    category: "event",
    tags: [
      "US Embassy",
      "American Cultural Day",
      "Qatar-US relations",
      "Independence Day",
      "panel discussion",
      "cultural exchange"
    ],
    notes: "Publication date not visible; event relates to July 4 celebrations and 50 years of Qatar-US diplomatic relations."
  },

  {
    id: "111",
    imageUrl: "/images/articles/111.jpg",
    title: "Qatar's First Forest School at ISL Qatar Celebrates First Year Anniversary with #bigbmeetup",
    publication: "marhabaguideqatar",
    excerpt: "The International School of London Qatar played host to yet another episode of #bigbmeetup",
    fullArticleUrl: "www.marhaba.qa",
    category: "news",
    tags: [
      "Qatar",
      "forest school",
      "ISL Qatar",
      "anniversary",
      "bigbmeetup"
    ],
    notes: "Publication date is not provided and could not be determined from the image."
  },

  {
    id: "13",
    imageUrl: "/images/articles/13.jpg",
    title: "Don't come up with excuses. Don't say that I will start tomorrow. Start now!",
    excerpt: "Mudassir Raja gleans useful advice from experts at a Doha event ahead of the National Sport Day tomorrow.",
    category: "feature",
    tags: [
      "sports",
      "motivation",
      "fitness",
      "event",
      "Doha",
      "National Sport Day"
    ],
    notes: "No publication name or date explicitly provided; the context suggests around National Sport Day but exact date unknown."
  },

  {
    id: "20",
    imageUrl: "/images/articles/20.jpg",
    title: "Al Aziziya Boutique Hotel to host 3rd BigB MeetUp",
    publication: "THE PENINSULA",
    excerpt: "Al Aziziya Boutique Hotel, one of the most iconic hotels in Doha, will host the 3rd BigB MeetUp, a community initiative founded by Bosco Menezes, aiming to inspire, inform, and educate about good deeds through a unique event with special needs speakers.",
    category: "event",
    tags: [
      "BigB MeetUp",
      "Al Aziziya Boutique Hotel",
      "community",
      "special needs",
      "Doha",
      "Bosco Menezes"
    ],
    notes: "Publication date not specified; the article focuses on an upcoming event themed 'This Ability' with 4 special needs speakers and local partners."
  },

  {
    id: "21",
    imageUrl: "/images/articles/21.jpg",
    excerpt: "Panel discussion at meetup with co-organizer Ahmed Al Shahrani and guests including Mohammed Al Hayder, Faisal Al Kooheji, and Ismail bin Yusaf.",
    category: "event",
    tags: [
      "panel discussion",
      "meetup",
      "Qatar",
      "special needs",
      "volunteers"
    ],
    notes: "No clear publication or date visible; image shows a group photo with a caption mentioning the meetup."
  },

  {
    id: "31",
    imageUrl: "/images/articles/31.jpg",
    title: "Next #bigbmeetup celebrating Artists of Qatar themed on Qatar National day festivities",
    excerpt: "Children upcycled glass bottles at Barzan Towers, a Qatari Heritage site, learning to beautify them as part of the #bigbmeetup and Qatar Sustainability Week.",
    category: "event",
    tags: [
      "bigbmeetup",
      "Qatar",
      "sustainability",
      "heritage",
      "art",
      "recycling"
    ],
    notes: "No clear publication or date information available; content sourced from social media screen captures related to a community event."
  },

  {
    id: "45",
    imageUrl: "/images/articles/45.jpg",
    title: "BigBMeetup 5th edition to focus on ‘Artists of Qatar’",
    publication: "The Peninsula",
    excerpt: "The 5th edition of BigBMeetUp has been themed on celebrating the artists of Qatar, local and expatriate.",
    category: "event",
    tags: [
      "BigBMeetup",
      "Qatar",
      "Artists",
      "Exhibition",
      "Community"
    ],
    notes: "Publication date not visible; event to take place on January 11 with a 6-week exhibition following at The Museum's contemporary art space The White Majlis."
  },

  {
    id: "46",
    imageUrl: "/images/articles/46.jpg",
    title: "BigBMeetUp 5th edition to focus on ‘Artists in Qatar’",
    excerpt: "The 5th edition of BigBMeetUp will celebrate 'Artists in Qatar' at Sheikh Faisal Bin Qassim Al Thani Museum, starting January 1 with an exhibition and talks.",
    category: "event",
    tags: [
      "BigBMeetUp",
      "Artists",
      "Qatar",
      "Art Exhibition",
      "Sheikh Faisal Bin Qassim Al Thani Museum"
    ],
    notes: "Publication name and exact publication date not provided in the clipping."
  },

  {
    id: "47",
    imageUrl: "/images/articles/47.png",
    title: "احتفاء بـ «الفنانين في قطر»",
    publication: "الوطن",
    excerpt: "احتفل BigBMeetup الخامس في أول ديسمبر 2022 بالربط بين الفنانين في قطر.",
    category: "event",
    tags: [
      "فن",
      "قطر",
      "معرض",
      "فنانين",
      "BigBMeetup",
      "ترابط"
    ],
    notes: "التاريخ الدقيق غير مذكور صراحة، لكن المقال يشير إلى أن الحدث الخامس كان بتاريخ 1 ديسمبر."
  },

  {
    id: "49",
    imageUrl: "/images/articles/49.png",
    title: "إطلاق النسخة الخامسة لـ BigBMeetup بعنوان فنانون في قطر",
    excerpt: "أُطلقت النسخة الخامسة من لقاء BigBMeetup بالتعاون مع متحف الشيخ فيصل بن قاسم آل ثاني تحت عنوان 'فنانون في قطر' بمشاركة أكثر من 30 فناناً محلياً وعالمياً.",
    category: "event",
    tags: [
      "BigBMeetup",
      "فن",
      "فنانون",
      "قطر",
      "متحف الشيخ فيصل",
      "ثقافة",
      "فعاليات"
    ],
    notes: "معلومات التاريخ واسم الصحيفة غير متوفرة في المقال. المقال مكتوب بالعربية ويتحدث عن النسخة الخامسة من حدث BigBMeetup والفنانين في قطر."
  },

  {
    id: "5",
    imageUrl: "/images/articles/5.jpg",
    title: "Wellness Instameet held",
    publication: "Qatar Tribune",
    excerpt: "BOSCO Menezes organized a health and wellness Instameet at the Torch Hotel Doha with guest speakers including sports icon Mohamed Saadon al Kuwari and yoga practitioner Vishnu Prasad.",
    category: "event",
    tags: [
      "wellness",
      "instameet",
      "health",
      "Qatar",
      "social media",
      "influencers"
    ],
    notes: "No specific publication date is available."
  },

  {
    id: "68",
    imageUrl: "/images/articles/68.jpg",
    title: "Four prominent women in sports and wellness meet at #BigBMeetUp",
    publication: "The Peninsula Qatar",
    excerpt: "Excellent event on 'Championing Qatari Sportswomen' by #BigBMeetUp and @ISLQatar. @USEmbassyDoha is a strong supporter of women in sports and committed to empowering women and girls.",
    fullArticleUrl: "https://thepeninsulaqatar.com/article/14/02/...",
    category: "event",
    tags: [
      "Qatar",
      "women",
      "sports",
      "empowerment",
      "BigBMeetUp"
    ],
    notes: "Exact publication date unknown; event mentioned recently by Ambassador Greta C. Holtz and The Peninsula Qatar tweet dated 1 day ago."
  },

  {
    id: "79",
    imageUrl: "/images/articles/79.png",
    title: "ISL Qatar hosts Qatar’s popular community outreach initiative #bigbmeetup’s ‘Estedama’ themed edition during Qatar Sustainability Week",
    excerpt: "The event brought together many national and international authorities and enthusiasts to debate topics focused on sustainability in Qatar.",
    category: "event",
    tags: [
      "sustainability",
      "Qatar",
      "community outreach",
      "ISL Qatar",
      "bigbmeetup",
      "environment"
    ],
    notes: "No publication name or date visible in the clipping."
  }
];
